-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: May 20, 2022 at 03:26 PM
-- Server version: 5.7.36
-- PHP Version: 7.4.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `thibanglaia1`
--

-- --------------------------------------------------------

--
-- Table structure for table `cauhoi_dapan`
--

DROP TABLE IF EXISTS `cauhoi_dapan`;
CREATE TABLE IF NOT EXISTS `cauhoi_dapan` (
  `cau` int(11) NOT NULL,
  `nd_cauhoi` text COLLATE utf8_unicode_ci NOT NULL,
  `hinh_cauhoi` text COLLATE utf8_unicode_ci NOT NULL,
  `a` text COLLATE utf8_unicode_ci NOT NULL,
  `b` text COLLATE utf8_unicode_ci NOT NULL,
  `c` text COLLATE utf8_unicode_ci NOT NULL,
  `d` text COLLATE utf8_unicode_ci NOT NULL,
  `caudung` text COLLATE utf8_unicode_ci NOT NULL,
  `caudiemliet` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `cauhoi_dapan`
--

INSERT INTO `cauhoi_dapan` (`cau`, `nd_cauhoi`, `hinh_cauhoi`, `a`, `b`, `c`, `d`, `caudung`, `caudiemliet`) VALUES
(1, 'Phần của đường bộ được sử dụng cho các phương tiện giao thông qua lại là gi?', 'null', '1. Phần mặt đường và lề đường', '2. Phân đường xe chạy', '3. Phần đường xe cơ giới', 'null', 'b', 'null'),
(2, '“Làn đường” là gì?', 'null', '1. Là một phần của phần đường xe chạy được chia theo chiều dọc của đường, sử dụng cho xe chay', '2.Là một phần của phần đường xe chạy được chia theo chiều dọc của đường, có bề rộng đủ cho xe chạy an toàn', '3. Là một phần của phần đường xe chạy được chia theo chiều dọc của đường, có đủ bề rộng cho xe ô tô chạy an toàn', 'null', 'b', 'null'),
(3, 'Khái niệm \"Khổ giới hạn dường bộ được hiểu như thể nào là đúng?', 'null', '1. Là khoảng trống có kích thước giới hạn về chiều cao, chiều rộng của đường, cầu, bến phà, hầm đường bộ để các xe kể cả hàng hóa xếp trên xe đi qua được an toàn.', '2. Là khoảng trống có kích thước giới hạn về chiều rộng của đường, cầu, bến phà, hầm trên đường bộ để các xe kể cả hàng hóa xếp trên xe đi qua được an toàn', '3. Là khoảng trống có kích thước giới hạn về chiều cao của cầu, bến phà, hầm trên đường bộ để các xe đi qua được an toàn', 'null', 'a', 'null'),
(4, 'Trong các khái niệm dưới đây, \"dải phân cách” được hiểu như thế nào là đúng?', 'null', '1. Là bộ phận của đường để ngăn cách không cho các loại xe vào những nơi không được phép.', '2. Là bộ phận của đường để phân tách phần đường xe chạy và hành lang an toàn giao thông.', '3. Là bộ phận của đường để phân chia mặt đường thành hai chiều xe chạy riêng biệt hoặc để phân chia phần đường của xe cơ giới và xe thô sơ.', 'null', 'c', 'null'),
(5, '“Dải phân cách” trên đường bộ gồm những loại nào?', 'null', '1. Dải phân cách gồm loại cố định và loại di động.', '2. Dải phân cách gồm tường chống ồn, hộ lan cứng và hộ lan mềm..', '3. Dải phân cách gồm giá long môn và biển báo hiệu đường bộ.', 'null', 'a', 'null'),
(6, 'Người lái xe được hiểu như thế nào trong các khái niệm dưới đây?', 'null', '1. Là người điều khiển xe cơ giới', '2. Là người điều khiến xe thô sơ.', '3. Là người điều khiển xe có súc vật kéo.', 'null', 'a', 'null'),
(7, 'Đường mà trên đó phương tiện tham gia giao thông được các phương tiện giao thông đến từ hướng khác nhường đường khi qua nơi đường giao nhau, được cảm biến báo hiệu đường ưu tiên là loại đường gì?', 'null', '1. Đường không ưu tiên.', '2. Đường tỉnh lộ.', '3. Đường quốc lộ.', '4. Đường ưu tiên.', 'd', 'null'),
(8, 'Khái niệm “phương tiện giao thông cơ giới đường bộ” được hiểu thế nào là đúng?', 'null', '1. Gồm xe ô tô; máy kéo; xe mô tô hai bánh; xe mô tô ba bánh; xe gắn máy; xe cơ giới dùng cho người khuyết tật và xe máy chuyên dùng.', '2. Gồm xe ô tô; máy kéo; rơ moóc hoặc sơ mi rơ moóc được kéo bởi xe ô tô, máy kéo; xe mô tô hai bánh; xe mô tô ba bánh, xe gắn máy (kể cả xe máy điện) và các loại xe tương tự.', 'null', 'null', 'b', 'null'),
(9, 'Khái niệm “phương tiện giao thông thô sơ đường bộ” được hiểu thế nào là đúng?', 'null', '1. Gồm xe đạp (kể cả xe đạp máy, xe đạp điện), xe xích lô, xe lăn dùng cho người khuyết tật, xe súc vật kéo và các loại xe tương tự.', '2. Gồm xe đạp (kể cả xe đạp máy, xe đạp điện), xe gắn máy, xe cơ giới dùng cho người khuyết tật và xe máy chuyên dùng.', '3. Gồm xe ô tô, máy kéo, rơ moóc hoặc sơ mỉ rơ moóc được kéo bởi xe ô tô, máy kéo.', 'null', 'a', 'null'),
(10, '“Phương tiện tham gia giao thông đường bộ” gồm những loại nào?', 'null', '1. Phương tiện giao thông cơ giới đường bộ.', '2. Phương tiện giao thông thô sơ đường bộ và xe máy chuyên dùng.', '3.cả ý 1 và ý 2.', 'null', 'c', 'null'),
(11, '“Người tham gia giao thông đường bộ” gồm những đối tượng nào?', 'null', '1. Người điều khiển, người sử dụng phương tiện tham gia giao thông đường bộ.', '2. Người điều khiển, dẫn dắt súc vật; người đi bộ trên đường bộ.', '3. Cả ý 1 và ý 2.', 'null', 'c', 'null'),
(12, 'Người điều khiển phương tiện tham gia giao hông đường bộ” gồm những đối tượng nào dưới đây?', 'null', '1. Người điều khiển xe cơ giới, người điều khiển xe thô sơ.', '2. Người điều khiển xe máy chuyên dùng tham gia giao thông đường bộ.', '3. Cả ý 1 và ý 2', 'null', 'c', 'null'),
(13, 'Khái niệm “người điều khiển giao thông” được hiểu như thế nào là đúng?', 'null', '1. Là người điều khiển phương tiện tham gia giao thông tại nơi thi công, nơi ùn tắc giao thông, ở bến phà, tại cầu đường bộ đi chung với đường sắt.', '2. Là cảnh sát giao thông, người được giao nhiệm vụ hướng dẫn giao thông tại nơi thi công, nơi ùn tắc giao thông, ở bến phà, tại cầu đường bộ đi chung với đường sắt.', '3. Là người tham gia giao thông tại nơi thi công, nơi ùn tắc giao thông, ở bến phà, tại cầu đường bộ đi chung với đường sắt.', 'null', 'b', 'null'),
(14, 'Trong các khái niệm dưới đây khái niệm “dừng xe” được hiểu như thế nào là đúng?', 'null', '1. Là trạng thái đứng yên của phương tiện giao thông không giới hạn thời gian để cho người lên, xuống phương tiện, xếp dỡ hàng hóa hoặc thực hiện công việc khác.', '2. Là trạng thái đứng yên tạm thời của phương tiện giao thông trong một khoảng thời gian cần thiẽ! đủ để cho người lên, xuống phương tiện, xếp dỡ hàng hóa hoặc thực hiện công việc khác.', '3. Là trạng thái đứng yên của phương tiện giao thông không giới hạn thời gian giữa 02 lần vận chuyển hàng hóa hoặc hành khách.', 'null', 'b', 'null'),
(15, 'Khái niệm “đồ xe” được hiểu như thế nào là đúng quy tắc giao thông?', 'null', '1. Là trạng thái đứng yên của phương tiện giao thông có giới hạn trong một khoảng thời gian cần thiết đủ để cho người lên, xuống phương tiện đó, xếp dỡ hàng hóa hoặc thực hiện công việc khác.', '2. Là trạng thái đứng yên của phương tiện giao\nthông không giới hạn thời gian.', 'null', 'null', 'b', 'null'),
(16, 'Khái niệm “đường cao tốc” được hiểu như thế nào là đúng?', 'null', '1. Đường dành riêng cho xe ôtô và một số loại xe chuyên dùng được phép đi vào theo quy định của Luật Giao thông đường bộ.', '2. Có dải phân cách phân chia đường cho xe chạy hai chiều riêng biệt mà dải phân cách này xe không đi được lên trên; không giao nhau cùng mức với một hoặc một số đường khác.', '3. Được bố trí đầy đủ trang thiết bị phục vụ, bảo đảm giao thông liên tục, an toàn, rút ngắn thời gian hành trình và chỉ cho xe ra, vào ở những điểm nhất định.', '4. Tất cả các ý trên.', 'd', 'null'),
(17, 'Hành vi nào dưới đây bị nghiêm cấm?', 'null', '1. Đỗ xe trên đường phố', '2. Sử dụng xe đạp đi trên các tuyến quốc lộ có tốc độ cao.', '3. Làm hỏng (cố ý) cọc tiêu, gương cầu, dải\nphân cách.', '4. Sử dụng còi và quay đầu xe trong khu dân cư.', 'c', '1'),
(18, 'Hành vi đưa xe cơ giới, xe máy chuyên dùng không bảo đảm tiêu chuẩn an toàn kỹ thuật và bảo vệ môi trường vào tham gia giao thông đường bộ có bị nghiêm cấm hay không?', 'null', '1. Không nghiêm cấm.', '2. Bị nghiêm cấm.', '3. Bị nghiêm cấm tùy theo các tuyến đường.', '4. Bị nghiêm cấm tuỳ theo loại xe.', 'b', '1'),
(19, 'Cuộc đua xe chỉ được thực hiện khi nào?', 'null', '1. Diễn ra trên đường phố không có người qua lại.', '2. Được người dân ủng hộ.', '3. Được cơ quan có thẩm quyền cấp phép.', 'null', 'c', '1'),
(20, 'Người điều khiển phương tiện giao thông đường bộ mà trong cơ thể có chất ma túy có bị nghiêm cấm hay không?', 'null', '1. Bị nghiêm cấm.', '2. Không bị nghiêm cấm.', '3. Không bị nghiêm cấm, nếu có chất ma túy ở mức nhẹ, có thể điều khiển phương tiện tham gia giao thông.', 'null', 'a', '1'),
(21, 'Việc lái xe mô tô, ô tô, máy kéo ngay sau khi uống rượu, bia có được phép hay không?', 'null', '1. Không được phép.', '2. Chỉ được lái ở tốc độ chậm và quãng đường ngắn.', '3. Chỉ được lái nếu trong cơ thể có nồng độ cồn thấp.', 'null', 'a', '1'),
(22, 'Người điều khiển xe ô tô, mô tô, máy kéo trên đường mà trong máu hoặc hơi thở có nồng độ cồn có bị nghiêm cấm không?', 'null', '1. Bị nghiêm cấm.', '2. Không bị nghiêm cấm.', '3. Không bị nghiêm cấm, nếu nồng độ cồn trong máu ở mức nhẹ, có thể điều khiển phương tiện tham gia giao thông.', 'null', 'a', '1'),
(23, 'Sử dụng rượu, bia khi lái xe, nếu bị phát hiện thì bị xử lý như thế nào?', 'null', '1. Chỉ bị nhắc nhở.', '2. Bị xử phạt hành chính hoặc có thể bị xử lý hình sự tùy theo mức độ vi phạm.', '3. Không bị xử lý hình sự.', 'null', 'b', '1'),
(24, 'Theo Luật phòng chống tác hại của rượu, bia, đối tượng nào dưới đây bị cấm sử dụng rượu, bia khi tham gia giao thông?', 'null', '1. Người điều khiển: Xe ô tô, xe mô tô, xe đạp, xe gắn máy.', '2. Người ngồi phía sau người điều khiển xe cơ giới.', '3. Người đi bộ.', '4.Cả ý 1 và ý 2.', 'a', '1'),
(25, 'Hành vi giao xe cơ giới, xe máy chuyên dùng cho người không đủ điều kiện để điều khiển xe tham gia giao thông có được phép hay không?', 'null', '1. Chỉ được thực hiện nếu đã hướng dẫn đầy đủ.', '2. Không được phép.', '3. Được phép tùy từng trường hợp.', '4. Chỉ được phép thực hiện với thành viên trong gia đình.', 'b', '1'),
(26, 'Hành vi điều khiển xe cơ giới chạy quá tốc độ quy định, giành đường, vượt ẩu có bị nghiêm cấm hay không?', 'null', '1. Bị nghiêm cấm tùy từng trường hợp.', '2. Không bị nghiêm cấm.', '3. Bị nghiêm cấm.', 'null', 'c', '1'),
(27, 'Khi lái xe trên đường, người lái xe cần quan sát và bảo đảm tốc độ phương tiện như thế nào?', 'null', '1. Chỉ lớn hơn tốc độ tối đa cho phép khi đường vắng.', '2. Chỉ lớn hơn tốc độ tối đa cho phép vào ban đêm.', '3. Không vượt quá tốc độ cho phép.', 'null', 'c', '1'),
(28, 'Phương tiện giao thông đường bộ di chuyển với tốc độ thấp hơn phải đi như thế nào?', 'null', '1. Đi về phía bên trái.', '2. Đi về phía bên phải.', '3. Đi ở giữa.', 'null', 'b', '1'),
(29, 'Trên đường có nhiều làn đường, khi điêu khiển phương tiện ở tốc độ chậm bạn phải đi ở làn đường nào?', 'null', '1. Đi ở làn bên phải trong cùng.', '2. Đi ở làn phía bên trái.', '3. Đi ở làn giữa.', '4. Đi ở bất cứ làn nào nhưng phải bấm đèn cảnh báo nguy hiểm để báo hiệu cho các phương tiện khác.', 'a', '1'),
(30, 'Hành vi vượt xe tại các vị trí có tâm nhìn hạn chế, đường vòng, đầu dốc có bị nghiêm cấm hay không?', 'null', '1. Không bị nghiêm cấm.', '2. Không bị nghiêm cấm khi rất vội.', '3. Bị nghiêm cấm.', '4. Không bị nghiêm cấm khi khẩn cấp.', 'c', '1'),
(31, 'Khi lái xe trong khu đô thị và đông dân cư trừ các khu vực có biển cấm sử dụng còi, người lái xe được sử dụng còi như thế nào trong các trường hợp dưới đây?', 'null', '1. Từ 22 giờ đêm đến 5 giờ sáng.', '2. Từ 5 giờ sáng đến 22 giờ tối.', '3.  Từ 23 giờ đêm đến 5 giờ sáng hôm sau.', 'null', 'b', 'null'),
(32, 'Người lái xe sử dụng đèn như thế nào khi lái xe trong khu đô thị và đông dân cư vào ban đêm?', 'null', '1. Bất cứ đèn nào miễn là mắt nhìn rõ phía trước.', '2. Chỉ bật đèn chiếu xa (đèn pha) khi không nhìn rõ đường.', '3. Đèn chiếu xa (đèn pha) khi đường vắng, đèn pha chiếu gần (đèn cốt) khi có xe đi ngược\nchiều.', '4. Đèn chiếu gần (đèn cốt).', 'd', 'null'),
(33, 'Hành vi lắp đặt, sử dụng còi, đèn không đúng thiết kế của nhà sản xuất đối với từng loại xe cơ giới có được phép hay không?', 'null', '1. Được phép', '2. Không được phép.', '3. Được phép tùy từng trường hợp.', 'null', 'b', '1'),
(34, 'Trong trường hợp đặc biệt, để được lắp đặt, sử dụng còi, đèn khác thiết kế của nhà sản xuất đối với từng loại xe cơ giới bạn phải đảm bảo yêu cầu nào dưới đây?', 'null', '1. Phải đảm bảo phụ tùng do đúng nhà sản xuất đó cung cấp.', '2. Phải được chấp thuận của cơ quan có thẩm quyền.', '3. Phải là xe đăng ký và hoạt động tại các khu vực có địa hình phức tạp.', 'null', 'b', 'null'),
(35, 'Việc sản xuất, mua bán, sử dụng biển số xe cơ giới, xe máy chuyên dùng được quy định như thế nào trong Luật Giao thông đường bộ?', 'null', '1. Được phép sản xuất, sử dụng khi bị mất biển số.', '2. Được phép mua bán, sử dụng khi bị mất biển số.', '3. Nghiêm cấm sản xuất, mua bán, sử dụng trái phép.', 'null', 'c', '1'),
(36, 'Người lái xe không được vượt xe khác khi gặp trường hợp nào ghi ở dưới đây?', 'null', '1. Trên cầu hẹp có một làn xe. Nơi đường giao nhau, đường bộ giao nhau cùng mức với đường sắt; xe được quyền ưu tiên đang phát tín hiệu ưu tiên đi làm nhiệm vụ.', '2. Trên cầu có từ 02 làn xe trở lên; nơi đường bộ giao nhau không cùng mức với đường sắt; xe được quyền ưu tiên đang đi phía trước nhưng không phát tín hiệu ưu tiên.', '3. Trên đường có 2 làn đường được phân chia làn bằng vạch kẻ nét đứt.\n', 'null', 'a', '1'),
(37, 'Ở phần đường dành cho người đi bộ qua đường, trên cầu, đầu cầu, đường cao tốc, đường hẹp, đường dốc, tại nơi đường bộ giao nhau cùng mức với đường sắt có được quay đầu xe hay không?', 'null', '1. Được phép.', '2. Không được phép.', '3. Tùy từng trường hợp.', 'null', 'b', '1'),
(38, 'Bạn đang lái xe phía trước có một xe cảnh sát giao hông không phát tín hiệu ưu tiên bạn có được phép vượt hay không?', 'null', '1. Không được vượt.', '2. Được vượt khi đang đi trên cầu.', '3. Được phép vượt khi đi qua nơi giao nhau có ít phương tiện cùng tham gia giao thông.', '4. Được vượt khi đảm bảo an toàn.', 'd', 'null'),
(39, 'Bạn đang lái xe phía trước có một xe cứu thương đang phát tín hiệu ưu tiên bạn có được phép vượt hay không?', 'null', '1. Không được vượt.', '2. Được vượt khi đang đi trên cầu.', '3. Được phép vượt khi đi qua nơi giao nhau có ít phương tiện cùng tham gia giao thông.', '4. Được vượt khi đảm bảo an toàn.', 'a', 'null'),
(40, 'Người lái xe không được quay đầu xe trong các trường hợp nào dưới đây?', 'null', '1. Ở phần đường dành cho người đi bộ qua đường, trên cầu, đầu cầu, đường cao tốc, đường hẹp, đường dốc, tại nơi đường bộ giao nhau cùng mức với đường sắt.', '2. Ở phía trước hoặc phía sau của phần đường dành cho người đi bộ qua đường, trên đường quốc lộ, tại nơi đường bộ giao nhau không cùng mức với đường sắt.', '3.Cả ý 1 và ý 2.', 'null', 'a', '1'),
(41, 'Bạn đang lái xe trong khu dân cư, có đông xe qua lại, nếu muốn quay đầu xe bạn cần làm gì để tránh ùn tắc và đảm bảo an toàn giao thông?', 'null', '1. Đi tiếp đến điểm giao cắt gần nhất hoặc nơi có biển báo cho phép quay đầu xe.', '2. Bấm đèn khẩn cấp và quay đầu xe từ từ bảo đảm an toàn.', '3. Bấm còi liên tục khi quay đầu xe để cảnh báo các xe khác.', '4. Nhờ một người ra hiệu giao thông trên đường chậm lại trước khi quay đầu.', 'a', 'null'),
(42, 'Người lái xe không được lùi xe ở những khu vực nào dưới đây?', 'null', '1. Ở khu vực cho phép đỗ xe.', '2. Ở khu vực cấm dừng và trên phần đường dành cho người đi bộ qua đường.', '3. Nơi đường bộ giao nhau, đường bộ giao nhau cùng mức với đường sắt, nơi tầm nhìn bị che khuất, trong hầm đường bộ, đường cao tốc.', '4.cả ý 2 và ý 3.', 'd', 'null'),
(43, 'Người điều khiển phương tiện giao thông trên đường phố có được dừng xe, đỗ xe trên miệng cống thoát nước, miệng hầm của đường điện thoại, điện cao thế, chỗ dành riêng cho xe chữa cháy lấy nước hay không?', 'null', '1. Được dừng xe, đỗ xe trong trường hợp cần thiết.', '2. Không được dừng xe, đỗ xe.', '3. Được dừng xe, không được đỗ xe.', 'null', 'b', '1'),
(44, 'Khi xe đã kéo 1 xe hoặc xe đã kéo 1 rơ moóc, bạn có được phép kéo thêm xe (kể cả xe thô sơ) hoặc rơ moóc thứ hai hay không?', 'null', '1. Chỉ được thực hiện trên đường quốc lộ có hai làn xe một chiều.', '2. Chỉ được thực hiện trên đường cao tốc.', '3. Không được thực hiện vào ban ngày.', '4. Không được phép.', 'd', 'null'),
(45, 'Người điều khiển xe mô tô hai bánh, ba bánh, xe gắn máy có được phép sử dụng xe để kéo hoặc đẩy các phương tiện khác khi tham gia giao thông không?', 'null', '1. Được phép.', '2. Nếu phương tiện được kéo, đẩy có khối lượng nhỏ hơn phương tiện của mình.', '3. Tùy trường hợp.', '4. Không được phép.', 'd', '1'),
(46, 'Khi điều khiển xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy, những hành vi buông cả hai tay; sử dụng xe để kéo, đẩy xe khác, vật khác; sử dụng chân chống của xe quệt xuống đường khi xe đang chạy có được phép hay không?', 'null', '1. Được phép.', '2. Tùy trường hợp.', '3. Không được phép.', 'null', 'c', '1'),
(47, 'Khi điều khiển xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy, những hành vi nào không được phép?', 'null', '1. Buông cả hai tay; sử dụng xe để kéo, đẩy xe khác, vật khác; sử dụng chân chống của xe quệt xuống đường khi xe đang chạy.', '2. Buông một tay; sử dụng xe để chở người hoặc hàng hoá; để chân chạm xuống đất khi khởi hành.', '3. Đội mũ bảo hiểm; chạy xe đúng tốc độ quy định và chấp hành đúng quy tắc giao thông đường bộ.', '4. Chở người ngồi sau dưới 16 tuổi.', 'a', '1'),
(48, 'Người ngồi trên xe mô tô hai bánh, ba bánh, xe gắn máy khi tham gia giao thông có được mang, vác vật cồng kềnh hay không?', 'null', '1. Được mang, vác tùy trường hợp cụ thể.', '2. Không được mang, vác.', '3. Được mang, vác nhưng phải đảm bảo an toàn.', '4. Được mang vác tùy theo sức khỏe của bản thân.', 'b', '1'),
(49, 'Người ngồi trên xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy khi tham gia giao thông có được bám, kéo hoặc đẩy các phương tiện khác không?', 'null', '1. Được phép.\n', '2. Được bám trong trường hợp phương tiện của mình bị hỏng.', '3. Được kéo, đẩy trong trường hợp phương tiện khác bị hỏng.', '4. Không được phép.', 'd', '1'),
(50, 'Người ngồi trên xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy khi tham gia giao thông có được sử dụng ô khi trời mưa hay không?', 'null', '1. Được sử dụng.', '2. Chỉ người ngồi sau được sử dụng.', '3. Không được sử dụng.', '4. Được sử dụng nếu không có áo mưa.', 'c', '1'),
(51, 'Khi đang lên dốc người ngôi trên xe mô tô có được phép kéo theo người đang điều khiển xe đạp hay không?', 'null', '1. Chỉ được phép nếu cả hai đội mũ bảo hiểm.', '2. Không được phép.', '3. Chỉ được phép thực hiện trên đường thật vắng.', '4. Chỉ được phép khi người đi xe đạp đã quá mệt.', 'b', '1'),
(52, 'Hành vi sử dụng xe mô tô để kéo, đẩy xe mô tô khác bị hết xăng đến trạm mua xăng có được phép hay không?', 'null', '1. Chỉ được kéo nếu đã nhìn thấy trạm xăng.', '2. Chỉ được thực hiện trên đường vắng phương tiện cùng tham gia giao thông.', '3. Không được phép.', 'null', 'c', '1'),
(53, 'Hành vi vận chuyển đồ vật công kênh bằng xe mô tô, xe gắn máy khi tham gia giao thông có được phép hay không?', 'null', '1. Không được vận chuyển.\n', '2. Chỉ được vận chuyển khi đã chẳng buộc cẩn thận.\n', '3. Chỉ được vận chuyển vật cồng kềnh trên xe máy nếu khoảng cách về nhà ngắn hơn 2 km.', 'null', 'a', '1'),
(54, 'Người đủ bao nhiêu tuổi trở lên thì được điêu khiển xe ô tô tải, máy kéo có trọng tải từ 3.500 kg trở lên; xe hạng B2 kéo rơ moóc (FB2)?', 'null', '1.19 tuổi.', '2. 21 tuổi.', '3. 20tuổi.', 'null', 'b', 'null'),
(55, 'Người đủ bao nhiêu tuổi trở lên thì được điều khiển xe mô tô hai bánh, xe mô tô ba bánh có dung tích xi lanh từ 50 cm3 trở lên và các loại xe có kếtcấu tương tự; xe ô tô tải, máy kéo có trọng tải dưới 3.500 kg; xe ô tô chở người đến 9 chỗ ngồi?', 'null', '1.16 tuổi.', '2. 18 tuổi.', '3. 17 tuổi.', 'null', 'b', 'null'),
(56, 'Người lái xe ô tô chở người trên 30 chỗ ngồi (hạng E), lái xe hạng D kéo rơ moóc (FD) phải đủ bao nhiêu tuổi trở lên?', 'null', '1. 23 tuổi.', '2. 24 tuổi.', '3. 27 tuổi.', '4. 30 tuổi.', 'c', 'null'),
(57, 'Tuổi tối đa của người lái xe ô tô chở người trên 30 chỗ ngồi (hạng E) là bao nhiêu tuổi?', 'null', '1. 55 tuổi đối với nam và 50 tuổi đối với nữ.', '2. 55 tuổi đối với nam và nữ.', '3. 60 tuổi đối với nam và 55 tuổi đối với nữ.', '4. 45 tuổi đối với nam và 40 tuổi đối với nữ.', 'a', 'null'),
(58, 'Người lái xe chở người từ 10 đến 30 chỗ ngôi (hạng D), lái xe hạng C kéo rơ moóc (FC) phải đủ bao nhiêu tuổi trở lên?', 'null', '1.23 tuổi.', '2.24 tuổi.', '3.22 tuổi.', '4. 18 tuổi.', 'b', 'null'),
(59, 'Người đủ 16 tuổi được điều khiển các loại xe nào dưới đây?\n', 'null', '1 . Xe mô tô 2 bánh có dung tích xi-lanh từ 50 cm3 trở lên.', '2. Xe gắn máy có dung tích xi-lanh dưới 50 cm3.', '3. Xe ô tô tải dưới 3.500 kg; xe chở người đến 9 chỗ ngồi.', '4. Tất cả các ý nêu trên.', 'b', 'null'),
(60, 'Người có giấy phép lái xe mô tô hạng A1 không được phép điều khiển loại xe nào dưới đây?', 'null', '1. Xe mô tô có dung tích xi-lanh 125 cm3.', '2. Xe mô tô có dung tích xi-lanh từ 175 cm3 trở lên.', '3. Xe mô tô có dung tích xi-lanh 100 cm3.', 'null', 'b', 'null'),
(61, 'Người có giấy phép lái xe mô tô hạng A1 được phép điều khiển loại xe nào dưới đây?', 'null', 'Xe mô tô có dung tích xi-lanh từ 50 cm3 đến dưới 175 cm3.', '2. Xe mô tô ba bánh dành cho người khuyết tật.', '3. Cả ý 1và ý 2.', 'null', 'c', 'null'),
(62, 'Người có giấy phép lái xe mô tô hạng A2 được phép điều khiển loại xe nào dưới đây?', 'null', '1. Xe mô tô ba bánh.', '2. Xe mô tô hai bánh có dung tích xi lanh từ 175 cm3 trở lên và các loại xe quy định cho giấy phép lái xe hạng A1.', '3. Các loại máy kéo nhỏ có trọng tải đến 1.000 kg.', 'null', 'b', 'null'),
(63, 'Người có giấy phép lái xe mô tô hạng A3 được phép điều khiển loại xe nào dưới đây?', 'null', '1. Xe mô tô ba bánh.', '2. Xe mô tô hai bánh có dung tích xi lanh từ 175\ncm3 trở lên.', '3. Các loại máy kéo nhỏ có trọng tải đến 1.000\nkg', 'null', 'a', 'null'),
(64, 'Người có giấy phép lái xe hạng B1 số tự động được điều khiển loại xe nào?', 'null', '1. Ô tô số tự động chở người đến 9 chỗ ngồi, kể cả chỗ ngồi cho người lái xe; ô tô tải, kể cả ô tô tải chuyên dùng số tự động có trọng tải thiết kế dưới 3.500 kg; ô tô dùng cho người khuyết tật. Không được hành nghề lái xe.', '2. Ô tô số tự động chở người đến 9 chỗ ngồi, kể cả chỗ ngồi cho người lái xe; ô tô tải, kể cả ô tô tải chuyên dùng số tự động có trọng tải thiết kế dưới 3.500 kg; ô tô dùng cho người khuyết tật. Được hành nghề lái xe kinh doanh vận tải.', '3. Ô tô chở người đến 9 chỗ ngồi, kể cả chỗ ngồi cho người lái xe; ô tô tải, kể cả ô tô tải chuyên dùng có trọng tải thiết kế dưới 3.500 kg; ô tô dùng cho người khuyết tật.', 'null', 'a', 'null'),
(65, 'Người có giấy phép lái xe hạng B1 được điều khiển loại xe nào?', 'null', '1. Ô tô chở người đến 9 chỗ ngồi, kể cả chỗ ngồi cho người lái xe; ô tô tải, kể cả ô tô tải chuyên dùng có trọng tải thiết kế dưới 3.500 kg; máy kéo kéo một rơ moóc có trọng tải thiết kế dưới 3.500 kg. Được hành nghề lái xe.', '2. Ô tô chở người đến 9 chỗ ngồi, kể cả chỗ ngồi cho người lái xe; ô tô tải, kể cả ô tô tải chuyên dùng có trọng tải thiết kế dưới 3.500 kg; máy kéo kéo một rơ moóc có trọng tải thiết kế dưới 3.500 kg. Không hành nghề lái xe.', '3. Ô tô số tự động chở người đến 9 chỗ ngồi, kể cả chỗ ngồi cho người lái xe; ô tô tải, kể cả ô tô tải chuyên dùng số tự động có trọng tải thiết kế\ntrên 3.500 kg; ô tô dùng cho người khuyết tật.', 'null', 'b', 'null'),
(66, 'Người có giấy phép lái xe hạng B2 được điều khiển loại xe nào?', 'null', '1. Xe ô tô chở người trên 9 chỗ ngồi; xe ô tô tải; máy kéo có trọng tải trên 3.500 kg.', '2. Xe ô tô chở người đến 9 chỗ ngồi; xe ô tô tải; máy kéo có trọng tải dưới 3.500 kg.', '3. Xe ô tô chở người từ 10 đến 30 chỗ ngồi; xe ô tô tải; máy kéo có trọng tải trên 3.500 kg.', 'null', 'b', 'null'),
(67, 'Người có giấy phép lái xe hạng C được điều khiển loại xe nào?', 'null', '1. Xe ô tô chở người trên 9 chỗ ngồi; xe ô tô tải; máy kéo có trọng tải trên 3.500 kg.', '2. Xe ô tô chở người từ 10 đến 30 chỗ ngồi; xe ô tô tải; máy kéo có trọng tải trên 3.500 kg.', '3. Xe ô tô chở người đến 9 chỗ ngồi; xe ô tô tải; máy kéo có trọng tải trên 3.500 kg.', 'null', 'c', 'null'),
(68, 'Người có giấy phép lái xe hạng D được điều khiển loại xe nào dưới đây?', 'null', 'Xe ô tô chở người đến 30 chỗ ngồi, kể cả chỗ ngồi cho người lái xe; xe ô tô tải, máy kéo có trọng tải trên 3.500 kg.', '2. Xe ô tô chở người trên 30 chỗ ngồi; xe ô tô tải, máy kéo có trọng tải trên 3.500 kg.', '3. Xe kéo rơ moóc, ô tô đầu kéo kéo sơ mỉ rơ moóc và được điều khiển các loại xe theo quy định cho giấy phép lái xe hạng B1, B2, C và FB2.\n', 'null', 'a', 'null'),
(69, 'Người có giấy phép lái xe hạng E được điều khiển loại xe nào dưới đây?', 'null', '1. Xe kéo rơ moóc, ô tô đầu kéo kéo sơ mi rơ moóc và được điều khiển các loại xe theo quy định cho giấy phép lái xe hạng B1, B2, C và FB2.', '2. Xe ô tô chở người trên 30 chỗ ngồi; xe ô tô tải, máy kéo có trọng tải trên 3.500 kg.', '3. Xe kéo rơ moóc và được điều khiển các loại xe; ô tô chở khách nối toa và các loại xe quy định cho giấy phép lái xe hạng B1, B2, C, D, FB2, FD.', 'null', 'b', 'null'),
(70, 'Người có giấy phép lái xe hạng FC được điều khiến loại xe nào dưới đây?', 'null', '1. Các loại xe được quy định tại giấy phép lái xe hạng C có kéo rơ moóc, ô tô đầu kéo kéo sơ mi rơ moóc, ô tô chở khách nối toa và được điều khiển các loại xe quy định cho giấy phép lái xe hạng B1, B2 và FB2.', '2. Các loại xe được quy định tại giấy phép lái xe hạng C có kéo rơ moóc, ô tô đầu kéo kéo sơ mi rơ moóc và được điều khiển các loại xe quy định cho giấy phép lái xe hạng B1, B2 và FB2.', '3. Mô tô hai bánh, các loại xe được quy định tại giấy phép lái xe hạng C có kéo rơ moóc, ô tô đầu kéo kéo sơ mỉ rơ moóc và được điều khiển các loại xe quy định cho giấy phép lái xe hạng B1,B2và FB2.', '4. Tất cả các loại xe nêu trên.', 'b', 'null'),
(71, 'Biển báo hiệu có dạng hình tròn, viền đỏ, nền trắng, trên nền có hình vẽ hoặc chữ số, chữ viết màu đen là loại biển gì dưới đây?', 'cau71.png', '1. Biển báo nguy hiểm.', '2. Biển báo cấm.', '3. Biển báo hiệu lệnh.', '4. Biển báo chỉ dẫn.', 'b', 'null'),
(72, 'Biển báo hiệu hình tròn có nên xanh lam có hình vẽ màu trắng là loại biển gì dưới đây?', 'cau72.png', '1. Biển báo nguy hiểm.', '2. Biển báo cấm.', '3. Biển báo hiệu lệnh phải thi hành.', '4. Biển báo chỉ dẫn.', 'c', 'null'),
(73, 'Biển báo hiệu hình chữ nhật hoặc hình vuông hoặc hình mũi tên nền xanh lam là loại biển gì dưới đây?', 'cau73.png', '1. Biển báo nguy hiểm.', '2. Biển báo cấm.', '3. Biển báo hiệu lệnh phải thi hành.', '4. Biển báo chỉ dẫn.', 'd', 'null'),
(74, 'Khi điều khiển xe chạy trên đường, người lái xe phải mang theo các loại giấy tờ gì?', 'null', '1. Giấy chứng nhận tốt nghiệp khóa đào tạo của hạng xe đang điều khiển, đăng ký xe, giấy phép lưu hành xe.', '2. Giấy phép lái xe phù hợp với loại xe đó; lệnh vận chuyển, đăng ký xe, giấy chứng nhận kiểm tra chất lượng an toàn kỹ thuật và bảo vệ môi trường của xe cơ giới sau khi cải tạo; giấy phép vận chuyển (nếu loại xe đó cần phải có).', '3. Giấy phép lái xe phù hợp với loại xe đó, đăng ký xe, giấy chứng nhận kiểm định kỹ thuật và bảo vệ môi trường, giấy chứng nhận bảo hiểm trách nhiệm dân sự của chủ xe cơ giới và giấy phép vận chuyển (nếu loại xe đó cần phải có),  các giấy tờ phải còn giá trị sử dụng.', 'null', 'c', 'null'),
(75, 'Khi sử dụng giấy phép lái xe đã khai báo mất để điều khiển phương tiện cơ giới đường bộ, ngoài việc bị thu hồi giấy phép lái xe, chịu trách nhiệm trước pháp luật, người lái xe không được cấp giấy phép lái xe trong thời gian bao nhiêu năm?', 'null', '1.02năm.', '2.03năm.', '3.05năm.', '4. 04 năm.', 'c', 'null'),
(76, 'Khi gặp hiệu lệnh như dưới đây của cảnh sát giao thông thì người tham gia giao thông phải đi như thế nào là đúng quy tắc giao thông?', 'cau76.png', '1. Người tham gia giao thông ở các hướng phải dừng lại.', '2. Người tham gia giao thông ở các hướng được đi theo chiều gậy chỉ của cảnh sát giao thông.', '3. Người tham gia giao thông ở phía trước và phía sau người điều khiển được đi tất cả các hướng; giao thông ở phía bên phải và phía bên trái người điều khiển phải dừng lại.', '4. Người tham gia giao thông ở phía trước và phía sau người điều khiển phải dừng lại; giao thông ở phía bên phải và bên trái người điều khiển đươc đi tất cả các hướng.', 'd', 'null'),
(77, 'Khi gặp hiệu lệnh như dưới đây của cảnh sát giao thông thì người tham gia giao thông phải đi như thế nào là đúng quy tắc giao thông?', 'cau77.png', '1. Người tham gia giao thông ở hướng đối diện cảnh sát giao thông được đi, các hướng khác cần phải dừng lại.', '2. Người tham gia giao thông được rẽ phải theo chiều mũi tên màu xanh ở bục cảnh sát giao thông.', '3. Người tham gia giao thông ở các hướng đều phải dừng lại trừ các xe đã ở trong khu vự giao nhau.3. Người tham gia giao thông ở các hướng đều phải dừng lại trừ các xe đã ở trong khu vự giao nhau.', '4. Người ở hướng đối diện cảnh sát giao thông phải dừng lại, các hướng khác được đi trong đó có bạn.', 'c', 'null'),
(78, 'Trên đường giao thông, khi hiệu lệnh của người điều khiển giao thông trái với hiệu lệnh của đèn hoặc biển báo hiệu thì người tham gia giao thông phải chấp hành theo hiệu lệnh nào?', 'null', '1. Hiệu lệnh của người điều khiển giao thông.', '2. Hiệu lệnh của đèn điều khiển giao thông.', '3. Hiệu lệnh của biển báo hiệu đường bộ.', '4. Theo quyết định của người tham gia giao thông nhưng phải bảo đảm an toàn.', 'a', '1'),
(79, 'Tại nơi có biển báo hiệu cố định lại có báo hiệu tạm thời thì người tham gia giao thông phải chấp hành hiệu lệnh của báo hiệu nào?', 'null', '1. Biển báo hiệu cố định.', '2. Báo hiệu tạm thời.', 'null', 'null', 'b', 'null'),
(80, 'Trên đường có nhiều làn đường cho xe đi cùng chiều được phân biệt bằng vạch kẻ phân làn đường, người điều khiển phương tiện phải cho xe đi như thế nào?', 'null', '1. Cho xe đi trên bất kỳ làn đường nào hoặc giữa 02 làn đường nếu không có xe phía trước; khi cần thiết phải chuyển làn đường, người lái xe phải quan sát xe phía trước để bảo đảm an toàn.', '2. Phải cho xe đi trong một làn đường và chỉ\neđược chuyển làn đường ở những nơi cho phép;\nkhi chuyển làn phải có tín hiệu báo trước và\nphải bảo đảm an toàn.', '3. Phải cho xe đi trong một làn đường, khi cần thiểt phải chuyển làn đường, người lái xe phải quan sát xe phía trước để bảo đảm an toàn.', 'null', 'b', 'null'),
(81, 'Bạn đang lái xe trong khu vực đô thị từ 22 giờ đến 5 giờ sáng hôm sau và cần vượt một xe khác, bạn cần báo hiệu như thế nào để đảm bảo an toàn giao thông?', 'null', '1. Phải báo hiệu bằng đèn hoặc còi.', '2. Chỉ được báo hiệu băng còi.', '3. Phải báo hiệu bằng cả còi và đèn.', '4. Chỉ được báo hiệu bằng đèn.', 'd', 'null'),
(82, 'Khi điều khiển xe chạy trên đường biết có xe sau xin vượt nếu đủ điều kiện an toàn người lái xe phải làm gì?', 'null', '1 . Tăng tốc độ và ra hiệu cho xe sau vượt, không được gây trở ngại cho xe sau vượt.', '2. Người điều khiển phương tiện phía trước phải giảm tốc độ, đi sát về bên phải của phần\nđường xe chạy cho đến khi xe sau đã vượt qua, không được gây trở ngại cho xe sau vượt.', '3. Cho xe tránh về bên trái mình và ra hiệu cho xe sau vượt; nếu có chướng ngại vật phía trước hoặc thiếu điều kiện an toàn chưa cho vượt được phải ra hiệu cho xe sau biết; cấm gây trở ngại cho xe xin vượt.', 'null', 'b', 'null'),
(83, 'Trong khu dân cư, ở nơi nào cho phép người lái xe, người điều khiển xe máy chuyên dùng được quay đầu xe?', 'null', '1. Ở nơi đường giao nhau và nơi có biển báo cho phép quay đầu xe.', '2. Ở nơi có đường rộng để cho các loại xe chạy một chiều.', '3. Ở bất kỳ nơi nào.', 'null', 'a', 'null'),
(84, 'Người lái xe phải làm gì khi quay đầu xe trên cầu, đường ngầm hay khu vực đường bộ giao nhau cùng mức với đường sắt?', 'null', '1. Không được quay đầu xe.', '2. Lợi dụng chỗ rộng và phải có người làm tín hiệu sau xe để bảo đảm an toàn.', '3. Lợi dụng chỗ rộng có thể quay đầu được để quay đầu xe cho an toàn.', 'null', 'a', '1'),
(85, 'Khi muốn chuyển hướng, người lái xe phải thực hiện như thế nào để đảm bảo an toàn giao thông?', 'null', '1. Quan sát gương, ra tín hiệu chuyển hướng, quan sát an toàn và chuyển hướng.', '2. Quan sát gương, giảm tốc độ, ra tín hiệu chuyẽn hướng, quan sát an toàn và chuyển hướng.', '3. Quan sát gương, tăng tốc độ, ra tín hiệu và chuyển hướng.', 'null', 'b', 'null'),
(86, 'Khi lùi xe người lái xe phải làm gì để bảo đảm an toàn?', 'null', '1. Quan sát phía trước và cho lùi xe ở tốc độ chậm.', '2. Lợi dụng nơi đường giao nhau đủ chiều rộng để lùi.', '3. Phải quan sát phía sau, có tín hiệu cần thiết và chỉ nào thấy không nguy hiểm mới được lùi.\n', 'null', 'c', 'null'),
(87, 'Khi bạn nhìn thấy đèn phía sau xe ô tô có màu sáng trắng, ô tô đó đang trong tình trạng như thế', 'null', '1 . Đang phanh.', '2. Đang bật đèn sương mù.', '3. Đang chuẩn bị lùi hoặc đang lùi.', '4. Đang bị hỏng động cơ.', 'c', 'null'),
(88, 'Khi tránh xe đi ngược chiều, các xe phải nhường  đường như thế nào là đúng quy tắc giao thông?', 'null', '1. Nơi đường hẹp chỉ đủ cho một xe chạy và có chỗ tránh xe thì xe nào ở gần chỗ tránh hơn phải vào vị trí tránh, nhường đường cho xe kia đi.', '2. Xe xuống dốc phải nhường đường cho xe đang lên dốc; xe nào có chướng ngại vật phía trước phải nhường đường cho xe không có chướng ngại vật đi trước.', '3. Xe lên dốc phải nhường đường cho xe xuống dốc; xe nào không có chướng ngại vật phía trước phải nhường đường cho xe có chướng ngại vật đi trước', '4. cả ý 1 và ý 2.', 'd', 'null'),
(89, 'Bạn đang lái xe trên đường hẹp, xuống dốc và gặp một xe đang đi lên dốc, bạn cần làm gì?', 'null', '1. Tiếp tục đi vì xe lên dốc phải nhường đường cho mình.', '2. Nhường đường cho xe lên dốc.', '3. Chỉ nhường đường khi xe lên dốc nháy đèn.', 'null', 'b', 'null'),
(90, 'Tại nơi đường giao nhau, người lái xe đang đi trên đường không ưu tiên phải nhường đường như thế nào là đúng quy tắc giao thông?', 'null', '1. Nhường đường cho xe đi ở bên phải mình tới.', '2. Nhường đường cho xe đi ở bên trái mình tới.', '3. Nhường đường cho xe đi trên đường ưu tiên hoặc đường chính từ bất kỳ hướng nào tới.', 'null', 'c', 'null'),
(91, 'Tại nơi đường giao nhau không có báo hiệu đi theo vòng xuyến, người điều khiển phương tiện phải nhường đường như thế nào là đúng quy tắc giao thông?', 'null', '1. Phải nhường đường cho xe đi đến từ bên phải.', '2. Xe báo hiệu xin đường trước xe đó được đi trước.', '3. Phải nhường đường cho xe đi đến từ bên trái.', 'null', 'a', 'null'),
(92, 'Trên đoạn đường bộ giao nhau cùng mức với đường sắt, cầu đường bộ đi chung với đường sắt thì loại phương tiện nào được quyền ưu tiên đi trước?', 'null', '1. Phương tiện nào bên phải không vướng.', '2. Phương tiện nào ra tín hiệu xin đường trước.', '3. Phương tiện giao thông đường sắt.', 'null', 'c', '1'),
(93, 'Tại nơi đường bộ giao nhau cùng mức với đường sắt chỉ có đèn tín hiệu hoặc chuông báo hiệu, khi đèn tín hiệu màu đỏ đã bật sáng hoặc có tiếng chuông báo hiệu, người tham gia giao thông phải dừng lại ngay và giữ khoảng cách tối thiểu bao nhiêu mét tính từ ray gần nhất?', 'null', '1. 1.5mét.', '2. 3 mét.', '3.4 mét.', 'null', 'a', 'null'),
(94, 'Người lái xe phải làm gì khi điều khiển xe vào đường cao tốc?', 'null', '1. Phải có tín hiệu xin vào và phải nhường đường cho xe đang chạy trên đường; khi thấy an toàn mới cho xe nhập vào dòng xe ở làn đường sát mép ngoài; nếu có làn đường tăng tốc thì phải cho xe chạy trên làn đường đó trước khi vào làn đường của đường cao tốc.', '2. Phải có tín hiệu xin vào và phải nhanh chóng vượt xe đang chạy trên đường để nhập vào dòng xe ở làn đường sát mép ngoài; nếu có làn đường tăng tốc thì phải cho xe chạy qua làn đường đó để vào làn đường của đường cao tốc.2. Phải có tín hiệu xin vào và phải nhanh chóng vượt xe đang chạy trên đường để nhập vào dòng xe ở làn đường sát mép ngoài; nếu có làn đường tăng tốc thì phải cho xe chạy qua làn đường đó để vào làn đường của đường cao tốc.', 'null', 'null', 'a', '1'),
(95, 'Trên đường cao tốc, người lái xe phải dừng xe, đỗ xe như thế nào để đảm bảo an toàn giao thông?', 'null', '1. Không được dừng xe, đỗ xe hoặc chỉ được dừng xe, đỗ xe ở nơi đường rộng, nếu dừng, đỗ xe ở nơi đường hẹp phải sử dụng còi báo hiệu để người lái xe khác biết.', '2. Chỉ được dừng xe, đỗ xe ở nơi quy định, trường hợp buộc phải dừng xe, đỗ xe không đúng nơi quy định thì người lái xe phải đưa xe ra khỏi phần đường xe chạy, nếu không thể được thì phải báo hiệu để người lái xe khác biết.', '3. Chỉ được dừng xe, đỗ xe ở nơi đường rộng; trường hợp dừng xe, đỗ xe tại nơi đường hẹp phải đặt các chướng ngại vật trên đường để yêu cầu người lái xe khác giảm tốc độ để bảo đảm an toan', 'null', 'b', 'null'),
(96, 'Những trường hợp nào ghi ở dưới đây không được đi vào đường cao tốc trừ người, phương tiện, thiết bị phục vụ cho việc quản lý, bảo trì đường cao tốc?', 'null', '1. Người đi bộ, xe thô sơ, xe gắn máy, xe mô tô và máy kéo; xe máy chuyên dùng có tốc độ thiết kế nhỏ hơn 70km/h.', '2. Xe mô tô và xe máy chuyên dùng có tốc độ thiết kế lớn hơn 70km/h.', '3. Người đi bộ, xe thô sơ, xe gắn máy và xe ô tô.', 'null', 'a', 'null'),
(97, 'Người điều khiển phương tiện tham gia giao thông trong hầm đường bộ ngoài việc phải tuân thủ các quy tắc giao thông còn phải thực hiện những quy định nào dưới đây?', 'null', '1. Xe cơ giới, xe máy chuyên dùng phải bật đèn; xe thô sơ phải bật đèn hoặc có vật phát sáng báo hiệu; chỉ được dừng xe, đỗ xe ở nơi quy định.', '2. Xe cơ giới phải bật đèn ngay cả khi đường hầm sáng; phải cho xe chạy trên một làn đường và chỉ chuyển làn ở nơi được phép; được quay đầu xe, lùi xe khi cần thiết.', '3. Xe máy chuyên dùng phải bật đèn ngay cả khi đường hầm sáng; phải cho xe chạy trên một làn đường và chỉ chuyển làn ở nơi được phép; được quay đầu xe, lùi xe khi cần thiết.', 'null', 'a', 'null'),
(98, 'Người ngôi trên xe mô tô 2 bánh, xe gắn máy phải đội mũ bảo hiểm có cài quai đúng quy cách khi nào?', 'null', '1. Khi tham gia giao thông đường bộ.', '2. Chỉ khi đi trên đường chuyên dùng; đường cao tốc.', '3. Khi tham gia giao thông trên đường tỉnh lộ hoặc quốc lộ.', 'null', 'a', '1'),
(99, 'Người điều khiển xe mô tô hai bánh, xe gắn máy được phép chở tối đa 2 người trong những trường hợp nào?', 'null', '1. Chở người bệnh đi cấp cứu; trẻ em dưới 14 tuổi.', '2. Áp giải người có hành vi vi phạm pháp luật.', '3. cả ý 1và ý 2.', 'null', 'c', 'null'),
(100, 'Người điều khiển xe mô tô hai bánh, xe gắn máy không được thực hiện những hành vi nào dưới đây?', 'null', '1. Đi vào phần đường dành cho người đi bộ và phương tiện khác; sử dụng ô, điện thoại di động, thiết bị âm thanh (trừ thiết bị trợ thính), đi xe dàn hàng ngang.', '2. Chở 02 người; trong đó, có người bệnh đi cấp cứu hoặc trẻ em dưới 14 tuổi hoặc áp giải người có hành vi vi phạm pháp luật.', '3. Điều khiển phương tiện tham gia giao thông trên đường tỉnh lộ hoặc quốc lộ.', 'null', 'a', 'null');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
